# The Python Code Generated by the ai_eda_code_agent is to be pasted here and execute it.
# Do not forget to add "df = pd.read_csv("your-filename.csv")" after all the import statements in this code
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv("customer_transactions.csv")
# Dataset Overview
def dataset_overview(df):
    print("Shape of the dataset:", df.shape)
    print("\nColumn Information:")
    print(df.info())
    print("\nMissing Values:")
    print(df.isnull().sum())

# Summary Statistics
def summary_statistics(df):
    print("\nSummary Statistics for Numeric Columns:")
    print(df.describe())

# Categorical Analysis
def categorical_analysis(df):
    categorical_cols = ['transaction_type', 'category', 'payment_method', 'customer_segment', 'merchant_name', 'city']
    for col in categorical_cols:
        plt.figure(figsize=(10, 5))
        sns.countplot(data=df, x=col, order=df[col].value_counts().index)
        plt.title(f'Distribution of {col}')
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()
        plt.close()

# Time-Based Analysis
def time_based_analysis(df):
    df['transaction_date'] = pd.to_datetime(df['transaction_date'], format='%d-%m-%Y')
    df.set_index('transaction_date', inplace=True)
    monthly_transactions = df.resample('M').size()
    
    plt.figure(figsize=(12, 6))
    monthly_transactions.plot()
    plt.title('Monthly Transactions Over Time')
    plt.xlabel('Date')
    plt.ylabel('Number of Transactions')
    plt.grid()
    plt.tight_layout()
    plt.show()
    plt.close()

# Outlier Detection
def detect_outliers(df):
    Q1 = df['transaction_amount'].quantile(0.25)
    Q3 = df['transaction_amount'].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = df[(df['transaction_amount'] < lower_bound) | (df['transaction_amount'] > upper_bound)]
    
    plt.figure(figsize=(10, 5))
    sns.boxplot(x=df['transaction_amount'])
    plt.title('Boxplot of Transaction Amounts')
    plt.show()
    plt.close()
    
    return outliers

# Execute EDA Functions
dataset_overview(df)
summary_statistics(df)
categorical_analysis(df)
time_based_analysis(df)
outliers = detect_outliers(df)
print("\nOutliers in Transaction Amounts:")
print(outliers)